services:
  asr-got-mcp:
    build: .
    ports:
      - "8082:8082"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config  # Changed path to match expected structure in container
    environment:
      - PYTHONUNBUFFERED=1
      - MCP_SERVER_PORT=8082
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '6.0'
          memory: 16G
    networks:
      - backend

  js-client:
    container_name: js-client
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"  # Exposes static client on HTTP
    networks:
      - backend
    # env_file: ./client/.env  # Uncomment if .env file exists
    # This service serves static assets via nginx

networks:
  backend:
    name: claude-network
    external: true
